# ============================================================
# Flag-Antp ChIP-seq enrichment analysis
# Two-panel figure: Motif status and peak sharing
#
# Run from the 11_enrichment_analysis directory:
#   Rscript scripts/11_02_enrichment_statistics.R
#
# Inputs:
#   data/Motif_Containing_enrichment.tsv
#   data/Motif_Free_enrichment.tsv
#   data/Shared_enrichment.tsv
#   data/Unique_enrichment.tsv
#
# Outputs:
#   results/FlagAntp_motif_statistics.csv
#   results/FlagAntp_shared_statistics.csv
#   results/FlagAntp_statistical_tests.txt
#   results/FlagAntp_enrichment_combined.svg
# ============================================================

# 1. Install missing packages and load dependencies
# ============================================================

packages <- c(
  "ggplot2",
  "dplyr",
  "svglite",
  "patchwork"
)

new_packages <- packages[
  !packages %in% rownames(installed.packages())
]

if (length(new_packages) > 0) {
  install.packages(new_packages)
}

library(ggplot2)
library(dplyr)
library(svglite)
library(patchwork)

# Reproducible placement of jittered points
set.seed(123)

# 2. Input and output directories
# ============================================================

INPUT_DIR <- "data"
OUTPUT_DIR <- "results"

dir.create(
  OUTPUT_DIR,
  recursive = TRUE,
  showWarnings = FALSE
)

# 3. Import enrichment files
# ============================================================

# Read the TSV files generated by multiBigwigSummary.
# The final column contains the mean bigWig signal per BED interval.

read_enrichment <- function(file, category) {

  if (!file.exists(file)) {
    stop("Missing input file: ", file)
  }

  data <- read.delim(
    file,
    header = TRUE,
    check.names = FALSE
  )

  data.frame(
    Enrichment = as.numeric(data[[ncol(data)]]),
    Category = category
  )
}

# Panel A: Motif status

motif <- read_enrichment(
  file.path(INPUT_DIR, "Motif_Containing_enrichment.tsv"),
  "Motif-containing"
)

motif_free <- read_enrichment(
  file.path(INPUT_DIR, "Motif_Free_enrichment.tsv"),
  "Motif-free"
)

df_motif <- bind_rows(
  motif,
  motif_free
)

df_motif$Category <- factor(
  df_motif$Category,
  levels = c(
    "Motif-containing",
    "Motif-free"
  )
)

# Panel B: Shared versus non-shared peaks

shared <- read_enrichment(
  file.path(INPUT_DIR, "Shared_enrichment.tsv"),
  "Shared"
)

unique <- read_enrichment(
  file.path(INPUT_DIR, "Unique_enrichment.tsv"),
  "Non-shared"
)

df_shared <- bind_rows(
  shared,
  unique
)

df_shared$Category <- factor(
  df_shared$Category,
  levels = c(
    "Shared",
    "Non-shared"
  )
)

# Remove missing or non-finite values

df_motif <- df_motif %>%
  filter(is.finite(Enrichment))

df_shared <- df_shared %>%
  filter(is.finite(Enrichment))

# 4. Descriptive statistics
# ============================================================

calculate_stats <- function(data) {

  data %>%
    group_by(Category) %>%
    summarise(
      N = n(),
      Mean = mean(Enrichment),
      SD = sd(Enrichment),
      Median = median(Enrichment),
      Q1 = quantile(Enrichment, 0.25),
      Q3 = quantile(Enrichment, 0.75),
      Min = min(Enrichment),
      Max = max(Enrichment),
      .groups = "drop"
    )
}

stats_motif <- calculate_stats(df_motif)
stats_shared <- calculate_stats(df_shared)

print(stats_motif)
print(stats_shared)

write.csv(
  stats_motif,
  file.path(
    OUTPUT_DIR,
    "FlagAntp_motif_statistics.csv"
  ),
  row.names = FALSE
)

write.csv(
  stats_shared,
  file.path(
    OUTPUT_DIR,
    "FlagAntp_shared_statistics.csv"
  ),
  row.names = FALSE
)

# 5. Statistical tests
# ============================================================

# Two-sided Mann-Whitney U tests

test_motif <- wilcox.test(
  Enrichment ~ Category,
  data = df_motif,
  alternative = "two.sided",
  exact = FALSE,
  correct = FALSE
)

test_shared <- wilcox.test(
  Enrichment ~ Category,
  data = df_shared,
  alternative = "two.sided",
  exact = FALSE,
  correct = FALSE
)

print(test_motif)
print(test_shared)

# Format p-values for figure annotations

format_p <- function(p) {

  if (p < 0.0001) {
    return("p < 0.0001")
  }

  paste0(
    "p = ",
    sprintf("%.3f", p)
  )
}

p_motif <- format_p(test_motif$p.value)
p_shared <- format_p(test_shared$p.value)

# Save statistical results

capture.output(
  cat("Motif-containing versus motif-free peaks\n"),
  print(test_motif),
  cat("\nShared versus non-shared peaks\n"),
  print(test_shared),
  file = file.path(
    OUTPUT_DIR,
    "FlagAntp_statistical_tests.txt"
  )
)

# 6. Figure settings
# ============================================================

# Consistent colors across both panels

colors <- c(
  "Motif-containing" = "#3979A8",
  "Motif-free" = "#C58A4B",
  "Shared" = "#3979A8",
  "Non-shared" = "#C58A4B"
)

# Same Y-axis range for both panels

y_max <- max(
  df_motif$Enrichment,
  df_shared$Enrichment
)

y_limit <- max(
  5,
  ceiling(y_max * 1.15)
)

# Position of statistical annotations

y_bracket <- y_limit * 0.89
y_text <- y_limit * 0.94

# Common theme

plot_theme <- theme_classic(
  base_size = 12
) +
  theme(
    axis.title = element_text(
      size = 12,
      colour = "black"
    ),

    axis.text = element_text(
      size = 11,
      colour = "black"
    ),

    axis.line = element_line(
      linewidth = 0.5
    ),

    axis.ticks = element_line(
      linewidth = 0.5
    ),

    legend.position = "none",

    plot.margin = margin(
      12, 12, 12, 12
    )
  )

# 7. Reusable violin plot function
# ============================================================

make_violin <- function(
  data,
  p_label,
  panel_label
) {

  # Generate labels with sample sizes

  counts <- data %>%
    count(Category)

  x_labels <- setNames(
    paste0(
      counts$Category,
      "\n(n = ",
      counts$n,
      ")"
    ),
    counts$Category
  )

  ggplot(
    data,
    aes(
      x = Category,
      y = Enrichment,
      fill = Category
    )
  ) +

    # Violin plot
    geom_violin(
      trim = FALSE,
      alpha = 0.25,
      width = 0.8,
      colour = NA
    ) +

    # Individual peaks
    geom_jitter(
      aes(colour = Category),
      width = 0.12,
      size = 0.65,
      alpha = 0.25
    ) +

    # Embedded box plot
    geom_boxplot(
      width = 0.20,
      outlier.shape = NA,
      alpha = 0.7,
      colour = "black",
      linewidth = 0.5
    ) +

    scale_fill_manual(
      values = colors
    ) +

    scale_colour_manual(
      values = colors
    ) +

    scale_x_discrete(
      labels = x_labels
    ) +

    # Statistical comparison bracket
    annotate(
      "segment",
      x = 1,
      xend = 2,
      y = y_bracket,
      yend = y_bracket,
      linewidth = 0.4
    ) +

    annotate(
      "segment",
      x = 1,
      xend = 1,
      y = y_bracket - 0.08,
      yend = y_bracket,
      linewidth = 0.4
    ) +

    annotate(
      "segment",
      x = 2,
      xend = 2,
      y = y_bracket - 0.08,
      yend = y_bracket,
      linewidth = 0.4
    ) +

    annotate(
      "text",
      x = 1.5,
      y = y_text,
      label = p_label,
      size = 3.5
    ) +

    coord_cartesian(
      ylim = c(0, y_limit)
    ) +

    labs(
      x = NULL,
      y = "Mean ChIP/input ratio per IDR peak",
      tag = panel_label
    ) +

    plot_theme +

    theme(
      plot.tag = element_text(
        face = "bold",
        size = 15
      ),

      plot.tag.position = c(
        0.02, 0.98
      )
    )
}

# 8. Generate both panels
# ============================================================

# Panel A: Motif-containing versus motif-free

p1 <- make_violin(
  data = df_motif,
  p_label = p_motif,
  panel_label = "A"
)

# Panel B: Shared versus non-shared

p2 <- make_violin(
  data = df_shared,
  p_label = p_shared,
  panel_label = "B"
)

# 9. Combine panels
# ============================================================

combined_figure <- p1 + p2 +
  plot_layout(
    ncol = 2,
    widths = c(1, 1)
  )

# 10. Export figure
# ============================================================

ggsave(
  filename = file.path(
    OUTPUT_DIR,
    "FlagAntp_enrichment_combined.svg"
  ),
  plot = combined_figure,
  width = 10,
  height = 5,
  units = "in",
  device = svglite
)

# Display combined figure

print(combined_figure)

cat("\nEnrichment analysis completed successfully.\n")